name: panvimdoc

on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kwon-evan/dotfiles/nvim.lazy@main
        with:
          vimdoc: dotfiles/nvim.lazy
          pandoc: nvim.lazy/doc/panvimdoc.md
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
